### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by StarchierOrb**

### CODE REVIEW

**Comment by Stereowalker** [comment]
I won't be able to merge it now as there are changes that I've made to the English file that I haven't uploaded a to GitHub yet

**Comment by StarchierOrb** [comment]
ok, I will open a new PR when you update the translation file.

**Comment by Stereowalker** [comment]
Done, when you update the lang file, I'll update it in 7.1.1

**Comment by StarchierOrb** [comment]
I have updated the translation file.

**Pull request merged**
